### ISSUE TITLE
Separate packages for the specification/logic and Integrations?

### ISSUE THREAD

**Issue by dariogriffo** [baranacikgoz/PaginatedSearchAndFilter#1]
It will be good to have separate packages to allow integrations with other stores seamesly?
To start
PaginatedSearchAndFilter.Specification
PaginatedSearchAndFilter.EfCore

**Comment by baranacikgoz** [comment]
Actually, I was started with 4 packages called:
PaginatedSearchAndFilter.Models
PaginatedSearchAndFilter.Queryable
PaginatedSearchAndFilter.Specification
PaginatedSearchAndFilter.EFCore

I thought it was not necessary at the moment and reduced it to one package. But at this point, I am no longer alone, we can separate them. I'd prefer to separate them in this one repository. What do you think?

**Comment by dariogriffo** [comment]
Yes, for now I think single repo, multiple packages should suffice.

**Comment by baranacikgoz** [comment]
Ok. Then, I will split them

**Comment by baranacikgoz** [comment]
updated the structure
