### ISSUE TITLE
OrderBy should be KeyValue pair

### ISSUE THREAD

**Issue by mohamadrajpurwala** [baranacikgoz/PaginatedSearchAndFilter#2]
I think instead of only Array of string for Order By, It will be good if it has Key Value pair.

"orderBy": ["price", "rating"]

it should be
 "orderBy": [
{key:"price",desc:true},
{key:"rating",desc:false}
]

**Comment by baranacikgoz** [comment]
I love your idea. You can make a pr imo.

**Comment by baranacikgoz** [comment]
I've refactored orderBy to have its own class to enhance self-documentation
